package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'GptbotProject_Deploy'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("GptbotProject_Deploy")) {
    params {
        expect {
            password("env.GITHUB_TOKEN", "", label = "GitHub Token", description = "GitHub Personal Access Token for repository access")
        }
        update {
            password("env.GITHUB_TOKEN", "zxxaad55a75a688127f728578b85ed8fba2bb136a4b71d21129be199a31c20381df6dfd994ad67534b5775d03cbe80d301b", label = "GitHub Token", description = "GitHub Personal Access Token for repository access", display = ParameterDisplay.HIDDEN, readOnly = true)
        }
    }
}
