package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildFeatures.dockerRegistryConnections
import jetbrains.buildServer.configs.kotlin.buildFeatures.perfmon
import jetbrains.buildServer.configs.kotlin.buildSteps.dockerCommand
import jetbrains.buildServer.configs.kotlin.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.triggers.vcs
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'GptbotProject_Build'
in the project with id = 'GptbotProject', and delete the patch script.
*/
create(RelativeId("GptbotProject"), BuildType({
    id("GptbotProject_Build")
    name = "wwhatsapp-controller"

    vcs {
        root(RelativeId("GptbotProject_HttpsGithubComDev4teamAiWhatsappControllerRefsHeadsMaster"))
    }

    steps {
        gradle {
            name = "build"
            id = "build"
            tasks = "bootBuildImage"
        }
        dockerCommand {
            name = "tag"
            id = "tag"
            commandType = other {
                subCommand = "tag"
                commandArgs = "docker.io/library/whatsapp-controller:0.1.0 protonmath/whatsapp-controller:%build.number%"
            }
        }
        dockerCommand {
            name = "publish"
            id = "publish"
            commandType = push {
                namesAndTags = "protonmath/whatsapp-controller:%build.number%"
            }
        }
    }

    triggers {
        vcs {
        }
    }

    features {
        perfmon {
        }
        dockerRegistryConnections {
            cleanupPushedImages = true
            loginToRegistry = on {
                dockerRegistryId = "PROJECT_EXT_3"
            }
        }
    }
}))

