package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildFeatures.perfmon
import jetbrains.buildServer.configs.kotlin.triggers.vcs
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'GptbotProject_WhatsappController_Build'
in the project with id = 'GptbotProject_WhatsappController', and delete the patch script.
*/
create(RelativeId("GptbotProject_WhatsappController"), BuildType({
    id("GptbotProject_WhatsappController_Build")
    name = "Build"

    vcs {
        root(RelativeId("GptbotProject_WhatsappController_HttpsGithubComDev4teamAiWhatsappControllerRefsHeadsMaster"))
    }

    triggers {
        vcs {
        }
    }

    features {
        perfmon {
        }
    }
}))

