package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'GptbotProject_WwhatsappNode'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("GptbotProject_WwhatsappNode")) {
    requirements {
        remove {
            equals("env.AGENT_TYPE", "docker-build")
        }
        add {
            equals("env.AGENT_TYPE", "nodejs-build")
        }
    }
}
