package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.DockerSupportFeature
import jetbrains.buildServer.configs.kotlin.buildFeatures.dockerRegistryConnections
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Gptbot_Backend'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Gptbot_Backend")) {
    features {
        val feature1 = find<DockerSupportFeature> {
            dockerRegistryConnections {
                param("cleanupPushedImages", "true")
                param("dockerRegistryId", "PROJECT_EXT_3")
                param("loginToRegistry", "true")
            }
        }
        feature1.apply {
            loginToRegistry = on {
                dockerRegistryId = "PROJECT_EXT_3"
            }
            param("loginToRegistry", "")
            param("cleanupPushedImages", "")
            param("dockerRegistryId", "")
        }
    }
}
