package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'GptbotProject_Deploy'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("GptbotProject_Deploy")) {
    vcs {
        remove(RelativeId("GptbotProject_GptbotHelmGit"))
        add(RelativeId("GptbotProject_GptbotHelmGitSsh"))
    }
}
