package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Gptbot_DeployFrontend'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Gptbot_DeployFrontend")) {
    requirements {
        add {
            equals("env.AGENT_TYPE", "helm-deploy")
        }
    }
}
