package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'GptbotProject_Deploy'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("GptbotProject_Deploy")) {
    params {
        expect {
            param("env.APP_NAME", "wwhatsapp-app")
        }
        update {
            select("env.APP_NAME", "", display = ParameterDisplay.PROMPT,
                    options = listOf("wwhatsapp-app", "gpt-agent-api", "gpt-agent-ui"))
        }
        expect {
            select("env.CLUSTER_NAME", "developing", label = "Target Cluster", description = "Select the cluster to deploy to",
                    options = listOf("developing", "staging", "production"))
        }
        update {
            select("env.CLUSTER_NAME", "staging", label = "Target Cluster", description = "Select the cluster to deploy to", display = ParameterDisplay.PROMPT,
                    options = listOf("developing", "staging", "production"))
        }
        expect {
            param("env.VERSION_TO_DEPLOY", "")
        }
        update {
            text("env.VERSION_TO_DEPLOY", "", display = ParameterDisplay.PROMPT, allowEmpty = true)
        }
    }
}
