package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'ProtonMath_Frontend_TeacherUiV2_Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("ProtonMath_Frontend_TeacherUiV2_Build")) {
    params {
        expect {
            password("env.CRYPT_KEY", "zxx90fd640ddc84feb3bae26bf487de1654")
        }
        update {
            password("env.CRYPT_KEY", "credentialsJSON:7aaffa3d-1007-4e7d-949b-5a35f8bac73b")
        }
        expect {
            password("env.KEYCLOAK_CLIENT_SECRET", "zxxb1ef4e8195fe8dfbe37e9d5f92fdc63da6b2025e57cb2acec22934181b107177775d03cbe80d301b")
        }
        update {
            password("env.KEYCLOAK_CLIENT_SECRET", "credentialsJSON:6619ac37-20eb-4e15-85ea-97792555de3e")
        }
        expect {
            password("env.NEXTAUTH_SECRET", "zxx90fd640ddc84feb3bae26bf487de1654")
        }
        update {
            password("env.NEXTAUTH_SECRET", "credentialsJSON:7aaffa3d-1007-4e7d-949b-5a35f8bac73b")
        }
    }
}
