package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'ProtonMath_Backend_Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("ProtonMath_Backend_Build")) {
    params {
        expect {
            password("env.GH_TOKEN", "zxx8b917490812b4af1dee4d6c6a628840b20fec2d360dfb6bc18284b59651a4c2a47f1c6a8d404c9a4775d03cbe80d301b")
        }
        update {
            password("env.GH_TOKEN", "credentialsJSON:cea6d1bc-d8a7-45b4-a4a2-9fcb941ae4b7")
        }
    }
}
