package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.DockerRegistryConnection
import jetbrains.buildServer.configs.kotlin.projectFeatures.dockerRegistry
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        val feature1 = find<DockerRegistryConnection> {
            dockerRegistry {
                id = "PROJECT_EXT_3"
                name = "Docker Registry"
                userName = "protonmath"
                password = "zxxc0ce9241d87412ebc5a4bd5fa5ffed29"
            }
        }
        feature1.apply {
            password = "credentialsJSON:898461ab-6060-41c9-af85-ef16dbe53099"
        }
    }
}
