package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = 'GptbotProject_WhatsappController'
in the project with id = 'GptbotProject', and delete the patch script.
*/
create(RelativeId("GptbotProject"), Project({
    id("GptbotProject_WhatsappController")
    name = "Whatsapp Controller"
}))

