package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = 'ProtonMath_Frontend_TeacherUi'
in the project with id = 'ProtonMath_Frontend', and delete the patch script.
*/
create(RelativeId("ProtonMath_Frontend"), Project({
    id("ProtonMath_Frontend_TeacherUi")
    name = "teacher-ui"
}))

