package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.DockerRegistryConnection
import jetbrains.buildServer.configs.kotlin.projectFeatures.dockerRegistry
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with id = 'ProtonMathProject'
accordingly, and delete the patch script.
*/
changeProject(RelativeId("ProtonMathProject")) {
    features {
        val feature1 = find<DockerRegistryConnection> {
            dockerRegistry {
                id = "PROJECT_EXT_11"
                name = "Docker Registry"
                userName = "protonmath"
                password = "zxx5e244335597ac1e30345c418695c01fe083c51d26ee56b10396789d1aa194f59a07c29f646e3eb09"
            }
        }
        feature1.apply {
            password = "credentialsJSON:b2c095a0-9755-4f30-b3e3-bd469b310511"
        }
    }
}
