package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = 'TeamcityGeneral_ProtonMath_Frontend_StudentUi'
in the project with id = 'TeamcityGeneral_ProtonMath_Frontend', and delete the patch script.
*/
create(RelativeId("TeamcityGeneral_ProtonMath_Frontend"), Project({
    id("TeamcityGeneral_ProtonMath_Frontend_StudentUi")
    name = "student-ui"
}))

