package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = 'TeamcityGeneral_ProtonMath_Backend'
in the project with id = 'TeamcityGeneral_ProtonMath', and delete the patch script.
*/
create(RelativeId("TeamcityGeneral_ProtonMath"), Project({
    id("TeamcityGeneral_ProtonMath_Backend")
    name = "Backend"
}))

