package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'Gptbot_WwhatsappNodeGit'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("Gptbot_WwhatsappNodeGit")) {
    val expected = GitVcsRoot({
        id("Gptbot_WwhatsappNodeGit")
        name = "git@github.com:dev4team-ai/wwhatsapp-node.git"
        url = "git@github.com:dev4team-ai/wwhatsapp-node.git"
        branch = "%teamcity.build.branch%"
        branchSpec = """
            +:refs/heads/*
            +:refs/tags/*
        """.trimIndent()
        authMethod = uploadedKey {
            userName = "git"
            uploadedKey = "wwhatsapp-node"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        url = "https://github.com/dev4team-ai/wwhatsapp-node"
        checkoutSubmodules = GitVcsRoot.CheckoutSubmodules.IGNORE
        authMethod = token {
            userName = "oauth2"
            tokenId = "tc_token_id:CID_5d39b539391852e509211819e6a59e55:-1:cc38399d-0f31-4ffc-b2d6-8f22803478df"
        }
        param("teamcitySshKey", "")
    }

}
