package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'Gptbot_GptAgentApiGit'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("Gptbot_GptAgentApiGit")) {
    val expected = GitVcsRoot({
        id("Gptbot_GptAgentApiGit")
        name = "git@github.com:dev4team-ai/gpt-agent-api.git"
        url = "git@github.com:dev4team-ai/gpt-agent-api.git"
        branch = "refs/heads/master"
        authMethod = uploadedKey {
            userName = "git"
            uploadedKey = "gpt-agent-api"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        branchSpec = "*"
    }

}
