package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'GptbotProject_HttpsGithubComDev4teamAiWhatsappControllerRefsHeadsMaster'
in the project with id = 'GptbotProject', and delete the patch script.
*/
create(RelativeId("GptbotProject"), GitVcsRoot({
    id("GptbotProject_HttpsGithubComDev4teamAiWhatsappControllerRefsHeadsMaster")
    name = "https://github.com/dev4team-ai/whatsapp-controller#refs/heads/master"
    url = "https://github.com/dev4team-ai/whatsapp-controller"
    branch = "refs/heads/master"
    branchSpec = "refs/heads/*"
    authMethod = token {
        userName = "oauth2"
        tokenId = "tc_token_id:CID_5d39b539391852e509211819e6a59e55:-1:5a458da9-ef72-4eba-bc5f-44a60d22969b"
    }
}))

