package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'Gptbot_GptbotHelmGit'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("Gptbot_GptbotHelmGit")) {
    val expected = GitVcsRoot({
        id("Gptbot_GptbotHelmGit")
        name = "https://github.com/dev4team-ai/gptbot-helm.git"
        url = "https://github.com/dev4team-ai/gptbot-helm.git"
        branch = "refs/heads/main"
        authMethod = password {
            userName = "teamcity"
            password = "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"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        authMethod = token {
            userName = "teamcity"
            tokenId = "tc_token_id:CID_5d39b539391852e509211819e6a59e55:-1:d88865e4-c6a5-4310-82c8-96d3e7a31446"
        }
        param("secure:password", "")
    }

}
