package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'GptbotProject_GptbotHelmGit'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("GptbotProject_GptbotHelmGit")) {
    val expected = GitVcsRoot({
        id("GptbotProject_GptbotHelmGit")
        name = "gptbot-helm-vcs"
        url = "https://github.com/dev4team-ai/gptbot-helm.git"
        branch = "refs/heads/main"
        authMethod = token {
            userName = "oauth2"
            tokenId = "tc_token_id:CID_5d39b539391852e509211819e6a59e55:-1:01a2e53c-54c5-4705-9c23-fdd31f092a0d"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        url = "https://github.com/dev4team-ai/gptbot-helm"
        authMethod = token {
            userName = "oauth2"
            tokenId = "tc_token_id:CID_5d39b539391852e509211819e6a59e55:-1:490356fb-dfff-496a-8b86-735e36fdec21"
        }
    }

}
