package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'GptbotProject_WwhatsappNodeVcs'
in the project with id = 'GptbotProject', and delete the patch script.
*/
create(RelativeId("GptbotProject"), GitVcsRoot({
    id("GptbotProject_WwhatsappNodeVcs")
    name = "wwhatsapp-node-vcs"
    url = "https://github.com/dev4team-ai/wwhatsapp-node"
    branch = "refs/heads/main"
    authMethod = token {
        userName = "oauth2"
        tokenId = "tc_token_id:CID_5d39b539391852e509211819e6a59e55:-1:01a2e53c-54c5-4705-9c23-fdd31f092a0d"
    }
}))

