package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'GptbotProject_HttpsGithubComDev4teamAiChannelServiceRefsHeadsMaster'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("GptbotProject_HttpsGithubComDev4teamAiChannelServiceRefsHeadsMaster")) {
    val expected = GitVcsRoot({
        id("GptbotProject_HttpsGithubComDev4teamAiChannelServiceRefsHeadsMaster")
        name = "https://github.com/dev4team-ai/channel-service#refs/heads/master"
        url = "https://github.com/dev4team-ai/channel-service"
        branch = "refs/heads/master"
        branchSpec = "refs/heads/*"
        authMethod = token {
            userName = "oauth2"
            tokenId = "tc_token_id:CID_5d39b539391852e509211819e6a59e55:-1:5a458da9-ef72-4eba-bc5f-44a60d22969b"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        authMethod = token {
            userName = "oauth2"
            tokenId = "tc_token_id:CID_5d39b539391852e509211819e6a59e55:-1:6b6f8283-56c5-4a9c-9d60-0772b164fa4b"
        }
    }

}
