package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'Gptbot_GptbotHelmGit'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("Gptbot_GptbotHelmGit")) {
    val expected = GitVcsRoot({
        id("Gptbot_GptbotHelmGit")
        name = "https://github.com/dev4team-ai/gptbot-helm.git"
        url = "https://github.com/dev4team-ai/gptbot-helm.git"
        branch = "refs/heads/main"
        authMethod = password {
            userName = "teamcity"
            password = "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"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        authMethod = password {
            userName = "teamcity"
            password = "zxxac0b501ef9a679f4b938ec98ebb1eba7e083ec2ae7927636cd8a5c946e0e97e5a1f661febf147650248decbad477c5ba0a438dacb0f1ec092764b56e3e8e4685bf02ab55b31ed9e3e5dd864ab7549c2512b2688205b480ecdb5c0fd6c2f252a1"
        }
    }

}
