package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'GptbotProject_GptbotHelmGitSsh'
in the project with id = 'GptbotProject', and delete the patch script.
*/
create(RelativeId("GptbotProject"), GitVcsRoot({
    id("GptbotProject_GptbotHelmGitSsh")
    name = "gptbot-helm-git-ssh"
    url = "git@github.com:dev4team-ai/gptbot-helm.git"
    branch = "main"
    authMethod = uploadedKey {
        uploadedKey = "gpt-helm-updater"
    }
}))

