package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'TeamcityGeneral_HttpsGithubComProtoMath2021teamcityGeneralGitRefsHeadsMaster'
in the project with id = 'TeamcityGeneral', and delete the patch script.
*/
create(RelativeId("TeamcityGeneral"), GitVcsRoot({
    id("TeamcityGeneral_HttpsGithubComProtoMath2021teamcityGeneralGitRefsHeadsMaster")
    name = "https://github.com/ProtoMath2021/teamcity-general.git#refs/heads/master"
    url = "https://github.com/ProtoMath2021/teamcity-general.git"
    branch = "refs/heads/master"
    branchSpec = "refs/heads/*"
}))

